// <auto-generated />
using System;
using Accounting.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounting.Api.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260825044009_Layer0_TenancyEntitiesAccountsPeriods")]
    partial class Layer0_TenancyEntitiesAccountsPeriods
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("control_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_accounts_parent_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_tenant_id_code");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("LegalEntityId")
                        .HasDatabaseName("ix_periods_legal_entity_id");

                    b.HasIndex("FiscalYearId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_fiscal_year_id_sequence");

                    b.ToTable("periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_period_dates", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_auth_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.EntityAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LocalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_entity_accounts");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_entity_accounts_account_id");

                    b.HasIndex("LegalEntityId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_accounts_legal_entity_id_account_id");

                    b.ToTable("entity_accounts", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_years");

                    b.HasIndex("LegalEntityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_years_legal_entity_id_code");

                    b.ToTable("fiscal_years", null, t =>
                        {
                            t.HasCheckConstraint("ck_fiscal_year_dates", "end_date > start_date");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FinancialYearStartMonth")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_start_month");

                    b.Property<string>("FunctionalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("functional_currency")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_no");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_legal_entities");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_legal_entities_tenant_id_code");

                    b.ToTable("legal_entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_entity_fy_start_month", "financial_year_start_month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.PeriodEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_utc");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.HasKey("Id")
                        .HasName("pk_period_events");

                    b.HasIndex("ByUserId")
                        .HasDatabaseName("ix_period_events_by_user_id");

                    b.HasIndex("PeriodId", "AtUtc")
                        .HasDatabaseName("ix_period_events_period_id_at_utc");

                    b.ToTable("period_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_period_event_state_changed", "from_state <> to_state");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.Account", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_accounts_parent_id");

                    b.HasOne("Accounting.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_tenants_tenant_id");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Accounting.Api.Models.AccountingPeriod", b =>
                {
                    b.HasOne("Accounting.Api.Models.FiscalYear", "FiscalYear")
                        .WithMany("Periods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_periods_fiscal_years_fiscal_year_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_periods_legal_entities_legal_entity_id");

                    b.Navigation("FiscalYear");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.AppUser", b =>
                {
                    b.HasOne("Accounting.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Accounting.Api.Models.EntityAccount", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "Account")
                        .WithMany("EntityAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_accounts_accounts_account_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany("EntityAccounts")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_accounts_legal_entities_legal_entity_id");

                    b.Navigation("Account");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.FiscalYear", b =>
                {
                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany("FiscalYears")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiscal_years_legal_entities_legal_entity_id");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.LegalEntity", b =>
                {
                    b.HasOne("Accounting.Api.Models.Tenant", "Tenant")
                        .WithMany("Entities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_entities_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Accounting.Api.Models.PeriodEvent", b =>
                {
                    b.HasOne("Accounting.Api.Models.AppUser", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_period_events_users_by_user_id");

                    b.HasOne("Accounting.Api.Models.AccountingPeriod", "Period")
                        .WithMany("Events")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_period_events_periods_period_id");

                    b.Navigation("ByUser");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounting.Api.Models.Account", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EntityAccounts");
                });

            modelBuilder.Entity("Accounting.Api.Models.AccountingPeriod", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Accounting.Api.Models.FiscalYear", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Accounting.Api.Models.LegalEntity", b =>
                {
                    b.Navigation("EntityAccounts");

                    b.Navigation("FiscalYears");
                });

            modelBuilder.Entity("Accounting.Api.Models.Tenant", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
