// <auto-generated />
using System;
using Accounting.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounting.Api.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260825153533_Layer5_StockSecurity")]
    partial class Layer5_StockSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("ControlType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("control_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPostable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_postable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("system_role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_accounts_parent_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_tenant_id_code");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.AccountingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FiscalYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiscal_year_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("LegalEntityId")
                        .HasDatabaseName("ix_periods_legal_entity_id");

                    b.HasIndex("FiscalYearId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_fiscal_year_id_sequence");

                    b.ToTable("periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_period_dates", "end_date >= start_date");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AllocatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("allocated_at_utc");

                    b.Property<Guid>("AllocatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("allocated_by_user_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CustomerReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_receipt_id");

                    b.Property<decimal>("FunctionalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("functional_amount");

                    b.Property<decimal>("FxGainLossFunctional")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fx_gain_loss_functional");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<Guid?>("ReversesAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_allocation_id");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_allocations");

                    b.HasIndex("CustomerReceiptId")
                        .HasDatabaseName("ix_allocations_customer_receipt_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_allocations_journal_entry_id");

                    b.HasIndex("ReversesAllocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_allocations_reverses_allocation_id")
                        .HasFilter("reverses_allocation_id IS NOT NULL");

                    b.HasIndex("SalesInvoiceId")
                        .HasDatabaseName("ix_allocations_sales_invoice_id");

                    b.ToTable("allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_allocation_amount_nonzero", "amount <> 0");

                            t.HasCheckConstraint("ck_allocation_sign_matches_kind", "(reverses_allocation_id IS NULL AND amount > 0) OR (reverses_allocation_id IS NOT NULL AND amount < 0)");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalAuthId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_auth_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.CostConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CostLayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_layer_id");

                    b.Property<Guid>("OutMoveId")
                        .HasColumnType("uuid")
                        .HasColumnName("out_move_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_cost_consumptions");

                    b.HasIndex("CostLayerId")
                        .HasDatabaseName("ix_cost_consumptions_cost_layer_id");

                    b.HasIndex("OutMoveId")
                        .HasDatabaseName("ix_cost_consumptions_out_move_id");

                    b.ToTable("cost_consumptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_cost_consumption_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.CostLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdjustsLayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjusts_layer_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("quantity_received");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SourceMoveId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_move_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_cost_layers");

                    b.HasIndex("AdjustsLayerId")
                        .HasDatabaseName("ix_cost_layers_adjusts_layer_id");

                    b.HasIndex("SourceMoveId")
                        .HasDatabaseName("ix_cost_layers_source_move_id");

                    b.HasIndex("ItemId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_layers_item_id_sequence");

                    b.HasIndex("LegalEntityId", "ItemId")
                        .HasDatabaseName("ix_cost_layers_legal_entity_id_item_id");

                    b.ToTable("cost_layers", null, t =>
                        {
                            t.HasCheckConstraint("ck_cost_layer_cost", "unit_cost > 0");

                            t.HasCheckConstraint("ck_cost_layer_quantity_matches_kind", "(adjusts_layer_id IS NULL AND quantity_received > 0) OR (adjusts_layer_id IS NOT NULL AND quantity_received = 0)");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("billing_address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CreditTermDays")
                        .HasColumnType("integer")
                        .HasColumnName("credit_term_days");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_no");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_tenant_id_code");

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_customer_credit_terms", "credit_term_days >= 0");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.CustomerReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DocNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("doc_no");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(19, 10)
                        .HasColumnType("numeric(19,10)")
                        .HasColumnName("fx_rate");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Memo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memo");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_receipts");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("ix_customer_receipts_bank_account_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_receipts_customer_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_customer_receipts_journal_entry_id");

                    b.HasIndex("LegalEntityId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("ix_customer_receipts_legal_entity_id_doc_no")
                        .HasFilter("doc_no IS NOT NULL");

                    b.ToTable("customer_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_receipt_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_receipt_posted_is_complete", "(state = 'Draft' AND doc_no IS NULL AND journal_entry_id IS NULL) OR (state = 'Posted' AND doc_no IS NOT NULL AND journal_entry_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.EntityAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("LocalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_entity_accounts");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_entity_accounts_account_id");

                    b.HasIndex("LegalEntityId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_entity_accounts_legal_entity_id_account_id");

                    b.ToTable("entity_accounts", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.FiscalYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fiscal_years");

                    b.HasIndex("LegalEntityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_fiscal_years_legal_entity_id_code");

                    b.ToTable("fiscal_years", null, t =>
                        {
                            t.HasCheckConstraint("ck_fiscal_year_dates", "end_date > start_date");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_uom");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<Guid>("CostOfSalesAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_of_sales_account_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("InventoryAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CostOfSalesAccountId")
                        .HasDatabaseName("ix_items_cost_of_sales_account_id");

                    b.HasIndex("InventoryAccountId")
                        .HasDatabaseName("ix_items_inventory_account_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_items_tenant_id_code");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entry_no");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Memo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memo");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by_user_id");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source_document_type");

                    b.Property<Guid?>("SupersedesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_entry_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_journal_entries_period_id");

                    b.HasIndex("PostedByUserId")
                        .HasDatabaseName("ix_journal_entries_posted_by_user_id");

                    b.HasIndex("ReversesEntryId")
                        .HasDatabaseName("ix_journal_entries_reverses_entry_id");

                    b.HasIndex("SupersedesEntryId")
                        .HasDatabaseName("ix_journal_entries_supersedes_entry_id");

                    b.HasIndex("LegalEntityId", "EntryDate")
                        .HasDatabaseName("ix_journal_entries_legal_entity_id_entry_date");

                    b.HasIndex("LegalEntityId", "EntryNo")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entries_legal_entity_id_entry_no");

                    b.ToTable("journal_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_journal_entry_no_self_reference", "(reverses_entry_id IS NULL OR reverses_entry_id <> id) AND (supersedes_entry_id IS NULL OR supersedes_entry_id <> id)");

                            t.HasCheckConstraint("ck_journal_entry_reversal_has_reason", "reverses_entry_id IS NULL OR reason_code IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FinancialYearStartMonth")
                        .HasColumnType("integer")
                        .HasColumnName("financial_year_start_month");

                    b.Property<string>("FunctionalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("functional_currency")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RegistrationNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registration_no");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_legal_entities");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_legal_entities_tenant_id_code");

                    b.ToTable("legal_entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_legal_entity_fy_start_month", "financial_year_start_month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.NumberCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_number");

                    b.Property<Guid>("NumberSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("number_series_id");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_number_counters");

                    b.HasIndex("NumberSeriesId", "PeriodKey")
                        .IsUnique()
                        .HasDatabaseName("ix_number_counters_number_series_id_period_key");

                    b.ToTable("number_counters", null, t =>
                        {
                            t.HasCheckConstraint("ck_number_counter_positive", "next_number > 0");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.NumberSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("document_type");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("format");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsGapless")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gapless");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ResetPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reset_policy");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_number_series");

                    b.HasIndex("LegalEntityId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_number_series_legal_entity_id_code");

                    b.HasIndex("LegalEntityId", "DocumentType", "IsActive")
                        .HasDatabaseName("ix_number_series_legal_entity_id_document_type_is_active");

                    b.ToTable("number_series", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.PeriodEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at_utc");

                    b.Property<Guid>("ByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("by_user_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.HasKey("Id")
                        .HasName("pk_period_events");

                    b.HasIndex("ByUserId")
                        .HasDatabaseName("ix_period_events_by_user_id");

                    b.HasIndex("PeriodId", "AtUtc")
                        .HasDatabaseName("ix_period_events_period_id_at_utc");

                    b.ToTable("period_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_period_event_state_changed", "from_state <> to_state");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.Posting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<decimal>("FunctionalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("functional_amount");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(19, 10)
                        .HasColumnType("numeric(19,10)")
                        .HasColumnName("fx_rate");

                    b.Property<Guid?>("IntercompanyEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("intercompany_entity_id");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid?>("TaxCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_code_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_postings");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_postings_account_id");

                    b.HasIndex("IntercompanyEntityId")
                        .HasDatabaseName("ix_postings_intercompany_entity_id");

                    b.HasIndex("JournalEntryId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_postings_journal_entry_id_line_no");

                    b.HasIndex("LegalEntityId", "AccountId")
                        .HasDatabaseName("ix_postings_legal_entity_id_account_id");

                    b.HasIndex("LegalEntityId", "CustomerId")
                        .HasDatabaseName("ix_postings_legal_entity_id_customer_id");

                    b.HasIndex("LegalEntityId", "SupplierId")
                        .HasDatabaseName("ix_postings_legal_entity_id_supplier_id");

                    b.ToTable("postings", null, t =>
                        {
                            t.HasCheckConstraint("ck_posting_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_posting_functional_amount_positive", "functional_amount > 0");

                            t.HasCheckConstraint("ck_posting_fx_rate_positive", "fx_rate > 0");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.SalesInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("doc_no");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(19, 10)
                        .HasColumnType("numeric(19,10)")
                        .HasColumnName("fx_rate");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("Memo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("memo");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoices");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_invoices_customer_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_sales_invoices_journal_entry_id");

                    b.HasIndex("LegalEntityId", "DocDate")
                        .HasDatabaseName("ix_sales_invoices_legal_entity_id_doc_date");

                    b.HasIndex("LegalEntityId", "DocNo")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoices_legal_entity_id_doc_no")
                        .HasFilter("doc_no IS NOT NULL");

                    b.ToTable("sales_invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_invoice_due_after_doc", "due_date >= doc_date");

                            t.HasCheckConstraint("ck_sales_invoice_posted_is_complete", "(state = 'Draft' AND doc_no IS NULL AND journal_entry_id IS NULL) OR (state = 'Posted' AND doc_no IS NOT NULL AND journal_entry_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.SalesInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RevenueAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("revenue_account_id");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_invoice_id");

                    b.Property<Guid?>("TaxCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_code_id");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tax_rate");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_invoice_lines");

                    b.HasIndex("RevenueAccountId")
                        .HasDatabaseName("ix_sales_invoice_lines_revenue_account_id");

                    b.HasIndex("TaxCodeId")
                        .HasDatabaseName("ix_sales_invoice_lines_tax_code_id");

                    b.HasIndex("SalesInvoiceId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_invoice_lines_sales_invoice_id_line_no");

                    b.ToTable("sales_invoice_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoice_line_price", "unit_price > 0");

                            t.HasCheckConstraint("ck_invoice_line_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_invoice_line_tax_rate_matches_code", "(tax_code_id IS NULL AND tax_rate = 0) OR tax_code_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.StockMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<DateOnly>("MovedOn")
                        .HasColumnType("date")
                        .HasColumnName("moved_on");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at_utc");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by_user_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("source_document_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_moves");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_stock_moves_item_id");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_stock_moves_journal_entry_id");

                    b.HasIndex("LegalEntityId", "ItemId", "MovedOn")
                        .HasDatabaseName("ix_stock_moves_legal_entity_id_item_id_moved_on");

                    b.ToTable("stock_moves", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_move_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.TaxCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid?>("InputAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OutputAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_account_id");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("rate");

                    b.Property<Guid>("TaxRegimeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_regime_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tax_codes");

                    b.HasIndex("InputAccountId")
                        .HasDatabaseName("ix_tax_codes_input_account_id");

                    b.HasIndex("OutputAccountId")
                        .HasDatabaseName("ix_tax_codes_output_account_id");

                    b.HasIndex("TaxRegimeId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tax_codes_tax_regime_id_code");

                    b.ToTable("tax_codes", null, t =>
                        {
                            t.HasCheckConstraint("ck_tax_code_dates", "effective_to IS NULL OR effective_to >= effective_from");

                            t.HasCheckConstraint("ck_tax_code_has_output_account", "rate = 0 OR output_account_id IS NOT NULL");

                            t.HasCheckConstraint("ck_tax_code_rate", "rate >= 0 AND rate <= 100");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.TaxRegime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<bool>("InputReclaimable")
                        .HasColumnType("boolean")
                        .HasColumnName("input_reclaimable");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tax_regimes");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tax_regimes_tenant_id_code");

                    b.ToTable("tax_regimes", null, t =>
                        {
                            t.HasCheckConstraint("ck_tax_regime_dates", "effective_to IS NULL OR effective_to >= effective_from");
                        });
                });

            modelBuilder.Entity("Accounting.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Accounting.Api.Models.Account", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_accounts_parent_id");

                    b.HasOne("Accounting.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_tenants_tenant_id");

                    b.Navigation("Parent");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Accounting.Api.Models.AccountingPeriod", b =>
                {
                    b.HasOne("Accounting.Api.Models.FiscalYear", "FiscalYear")
                        .WithMany("Periods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_periods_fiscal_years_fiscal_year_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_periods_legal_entities_legal_entity_id");

                    b.Navigation("FiscalYear");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.Allocation", b =>
                {
                    b.HasOne("Accounting.Api.Models.CustomerReceipt", "CustomerReceipt")
                        .WithMany()
                        .HasForeignKey("CustomerReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_customer_receipts_customer_receipt_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_allocations_journal_entries_journal_entry_id");

                    b.HasOne("Accounting.Api.Models.Allocation", "ReversesAllocation")
                        .WithMany()
                        .HasForeignKey("ReversesAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_allocations_allocations_reverses_allocation_id");

                    b.HasOne("Accounting.Api.Models.SalesInvoice", "SalesInvoice")
                        .WithMany()
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_sales_invoices_sales_invoice_id");

                    b.Navigation("CustomerReceipt");

                    b.Navigation("JournalEntry");

                    b.Navigation("ReversesAllocation");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("Accounting.Api.Models.AppUser", b =>
                {
                    b.HasOne("Accounting.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Accounting.Api.Models.CostConsumption", b =>
                {
                    b.HasOne("Accounting.Api.Models.CostLayer", "CostLayer")
                        .WithMany("Consumptions")
                        .HasForeignKey("CostLayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cost_consumptions_cost_layers_cost_layer_id");

                    b.HasOne("Accounting.Api.Models.StockMove", "OutMove")
                        .WithMany()
                        .HasForeignKey("OutMoveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cost_consumptions_stock_moves_out_move_id");

                    b.Navigation("CostLayer");

                    b.Navigation("OutMove");
                });

            modelBuilder.Entity("Accounting.Api.Models.CostLayer", b =>
                {
                    b.HasOne("Accounting.Api.Models.CostLayer", "AdjustsLayer")
                        .WithMany()
                        .HasForeignKey("AdjustsLayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cost_layers_cost_layers_adjusts_layer_id");

                    b.HasOne("Accounting.Api.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cost_layers_items_item_id");

                    b.HasOne("Accounting.Api.Models.StockMove", "SourceMove")
                        .WithMany()
                        .HasForeignKey("SourceMoveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cost_layers_stock_moves_source_move_id");

                    b.Navigation("AdjustsLayer");

                    b.Navigation("Item");

                    b.Navigation("SourceMove");
                });

            modelBuilder.Entity("Accounting.Api.Models.CustomerReceipt", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_receipts_accounts_bank_account_id");

                    b.HasOne("Accounting.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_receipts_customers_customer_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_receipts_journal_entries_journal_entry_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_receipts_legal_entities_legal_entity_id");

                    b.Navigation("BankAccount");

                    b.Navigation("Customer");

                    b.Navigation("JournalEntry");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.EntityAccount", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "Account")
                        .WithMany("EntityAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_accounts_accounts_account_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany("EntityAccounts")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entity_accounts_legal_entities_legal_entity_id");

                    b.Navigation("Account");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.FiscalYear", b =>
                {
                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany("FiscalYears")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiscal_years_legal_entities_legal_entity_id");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.Item", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "CostOfSalesAccount")
                        .WithMany()
                        .HasForeignKey("CostOfSalesAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_accounts_cost_of_sales_account_id");

                    b.HasOne("Accounting.Api.Models.Account", "InventoryAccount")
                        .WithMany()
                        .HasForeignKey("InventoryAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_accounts_inventory_account_id");

                    b.Navigation("CostOfSalesAccount");

                    b.Navigation("InventoryAccount");
                });

            modelBuilder.Entity("Accounting.Api.Models.JournalEntry", b =>
                {
                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_legal_entities_legal_entity_id");

                    b.HasOne("Accounting.Api.Models.AccountingPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_periods_period_id");

                    b.HasOne("Accounting.Api.Models.AppUser", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entries_users_posted_by_user_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "Reverses")
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_reverses_entry_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_journal_entries_journal_entries_supersedes_entry_id");

                    b.Navigation("LegalEntity");

                    b.Navigation("Period");

                    b.Navigation("PostedBy");

                    b.Navigation("Reverses");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("Accounting.Api.Models.LegalEntity", b =>
                {
                    b.HasOne("Accounting.Api.Models.Tenant", "Tenant")
                        .WithMany("Entities")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_legal_entities_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Accounting.Api.Models.NumberCounter", b =>
                {
                    b.HasOne("Accounting.Api.Models.NumberSeries", "NumberSeries")
                        .WithMany("Counters")
                        .HasForeignKey("NumberSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_number_counters_number_series_number_series_id");

                    b.Navigation("NumberSeries");
                });

            modelBuilder.Entity("Accounting.Api.Models.NumberSeries", b =>
                {
                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_number_series_legal_entities_legal_entity_id");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.PeriodEvent", b =>
                {
                    b.HasOne("Accounting.Api.Models.AppUser", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_period_events_users_by_user_id");

                    b.HasOne("Accounting.Api.Models.AccountingPeriod", "Period")
                        .WithMany("Events")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_period_events_periods_period_id");

                    b.Navigation("ByUser");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounting.Api.Models.Posting", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_postings_accounts_account_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "IntercompanyEntity")
                        .WithMany()
                        .HasForeignKey("IntercompanyEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_postings_legal_entities_intercompany_entity_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "JournalEntry")
                        .WithMany("Postings")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_postings_journal_entries_journal_entry_id");

                    b.Navigation("Account");

                    b.Navigation("IntercompanyEntity");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Accounting.Api.Models.SalesInvoice", b =>
                {
                    b.HasOne("Accounting.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoices_customers_customer_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_invoices_journal_entries_journal_entry_id");

                    b.HasOne("Accounting.Api.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoices_legal_entities_legal_entity_id");

                    b.Navigation("Customer");

                    b.Navigation("JournalEntry");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("Accounting.Api.Models.SalesInvoiceLine", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "RevenueAccount")
                        .WithMany()
                        .HasForeignKey("RevenueAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_lines_accounts_revenue_account_id");

                    b.HasOne("Accounting.Api.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_invoice_lines_sales_invoices_sales_invoice_id");

                    b.HasOne("Accounting.Api.Models.TaxCode", "TaxCode")
                        .WithMany()
                        .HasForeignKey("TaxCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_invoice_lines_tax_codes_tax_code_id");

                    b.Navigation("RevenueAccount");

                    b.Navigation("SalesInvoice");

                    b.Navigation("TaxCode");
                });

            modelBuilder.Entity("Accounting.Api.Models.StockMove", b =>
                {
                    b.HasOne("Accounting.Api.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_moves_items_item_id");

                    b.HasOne("Accounting.Api.Models.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_moves_journal_entries_journal_entry_id");

                    b.Navigation("Item");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Accounting.Api.Models.TaxCode", b =>
                {
                    b.HasOne("Accounting.Api.Models.Account", "InputAccount")
                        .WithMany()
                        .HasForeignKey("InputAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tax_codes_accounts_input_account_id");

                    b.HasOne("Accounting.Api.Models.Account", "OutputAccount")
                        .WithMany()
                        .HasForeignKey("OutputAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tax_codes_accounts_output_account_id");

                    b.HasOne("Accounting.Api.Models.TaxRegime", "TaxRegime")
                        .WithMany("Codes")
                        .HasForeignKey("TaxRegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tax_codes_tax_regimes_tax_regime_id");

                    b.Navigation("InputAccount");

                    b.Navigation("OutputAccount");

                    b.Navigation("TaxRegime");
                });

            modelBuilder.Entity("Accounting.Api.Models.Account", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("EntityAccounts");
                });

            modelBuilder.Entity("Accounting.Api.Models.AccountingPeriod", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Accounting.Api.Models.CostLayer", b =>
                {
                    b.Navigation("Consumptions");
                });

            modelBuilder.Entity("Accounting.Api.Models.FiscalYear", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Accounting.Api.Models.JournalEntry", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("Accounting.Api.Models.LegalEntity", b =>
                {
                    b.Navigation("EntityAccounts");

                    b.Navigation("FiscalYears");
                });

            modelBuilder.Entity("Accounting.Api.Models.NumberSeries", b =>
                {
                    b.Navigation("Counters");
                });

            modelBuilder.Entity("Accounting.Api.Models.SalesInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Accounting.Api.Models.TaxRegime", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("Accounting.Api.Models.Tenant", b =>
                {
                    b.Navigation("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
